// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izywgpcghhwufznjtcgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eXdncGNnaGh3dWZ6bmp0Y2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMjM3MTUsImV4cCI6MjA1MTU5OTcxNX0.T0GH7lkM3t256q6oEV25zjgRooNXvZMmfUVPI07gpCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);